Traceback (most recent call last):
  File "/Users/joe/opt/anaconda3/envs/KLSN/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/joe/opt/anaconda3/envs/KLSN/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/joe/opt/anaconda3/envs/KLSN/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/joe/opt/anaconda3/envs/KLSN/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/joe/opt/anaconda3/envs/KLSN/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/joe/opt/anaconda3/envs/KLSN/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/joe/opt/anaconda3/envs/KLSN/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/joe/opt/anaconda3/envs/KLSN/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Columns for simulation type and events per channel.
column_names = ['sn_name', 'model', 'channel', 'counts']

events = pd.DataFrame(columns=column_names)
# Append 1 row for each channel.  I don't care if it's not efficient.  Who's reading this?
for i, file in enumerate(files):
    name = sn_names[i]
    df = pd.read_csv(file, sep=" ")
    model = df[:1]['model'].values[0]
    for chan in df['channel']:
        N = df[df['channel']==chan]['events'].values[0]
        row = {'sn_name': name, 'model': model, 'channel': chan, 'counts': N}
        events = events.append(row , ignore_index=True)
------------------


IndexError: list index out of range

